config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :sakes do
  resources :reviews, except: [:show, :index]
  end
  root 'sakes#index'
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :sake
end

app/models/sake.rb
class Sake < ActiveRecord::Base
  belongs_to :user
  has_many :reviews

  has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :sakes
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_sake
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.sake_id = @sake.id

    if @review.save
      redirect_to @sake
    else
      render :new 
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
	format.html { redirect_to @review, notice: 'Review was successfully updated.' }
	format.json { render :show, status: :ok, location: @review }
      else
	format.html { render :edit }
	format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    redirect_to root_path
  end

  private
  def set_review
    @review = Review.find(params[:id])
  end

  def set_sake
    @sake = Sake.find(params[:sake_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/sakes_controller.rb
class SakesController < ApplicationController
  before_action :set_sake, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @sakes = Sake.all
  end

  def show
    @reviews = Review.where(sake_id: @sake.id).order("created_at DESC")

    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @sake = current_user.sakes.build 
  end

  def edit
  end

  def create
    @sake = current_user.sakes.build(sake_params)

    respond_to do |format|
      if @sake.save
        format.html { redirect_to @sake, notice: 'Sake was successfully created.' }
        format.json { render :show, status: :created, location: @sake }
      else
        format.html { render :new }
        format.json { render json: @sake.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @sake.update(sake_params)
        format.html { redirect_to @sake, notice: 'Sake was successfully updated.' }
        format.json { render :show, status: :ok, location: @sake }
      else
        format.html { render :edit }
        format.json { render json: @sake.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @sake.destroy
    respond_to do |format|
      format.html { redirect_to sakes_url, notice: 'Sake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_sake
      @sake = Sake.find(params[:id])
    end

    def sake_params
      params.require(:sake).permit(:name, :catchcopy, :home, :url, :classification, :alcohol, :ingredient, :rice, :seimaibuai, :description, :size, :maker, :rating, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "SakeDict."
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sakes_helper.rb
module SakesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SakeDict.", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "銘柄の追加", new_sake_path, class: "active" %></li>
          <li><%= link_to "アカウント", edit_user_registration_path %></li>
	        <li><%= link_to "ログアウト", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for([@sake,@review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div>
    <br>
  </div>
    <%= f.label "レート" %><br>
    <div id="star-rating"></div>
    <br>
  </div>
  <div class="field">
    <%= f.label "コメント" %><br>
    <%= f.text_area :comment , class: "form-control" %>
  </div>
  <div>
    <br>
  </div>
  <div class="actions">
    <%= f.submit "投稿する", class: "btn btn-large btn-success"%>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'もどる', sake_path(@sake) %>

app/views/reviews/new.html.erb
<h1>レビュー投稿</h1>

<%= render 'form' %>

<%= link_to 'もどる', sake_path(@sake) %>

app/views/sakes/_form.html.erb
<%= form_for @sake, html: { multipart: true } do |f| %>
  <% if @sake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sake.errors.count, "error") %> prohibited this sake from being saved:</h2>

      <ul>
      <% @sake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "画像" %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label "銘柄名" %><br>
    <%= f.text_field :name , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "キャッチコピー" %><br>
    <%= f.text_area :catchcopy , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "詳細説明" %><br>
    <%= f.text_area :description , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "URL" %><br>
    <%= f.url_field :url , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "産地" %><br>
    <%= f.text_field :home , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "蔵元" %><br>
    <%= f.text_field :maker , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "分類" %><br>
    <%= f.text_field :classification , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "アルコール度数" %><br>
    <%= f.number_field :alcohol , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "原料名" %><br>
    <%= f.text_field :ingredient , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "原料米" %><br>
    <%= f.text_field :rice , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label "精米歩合(%)" %><br>
    <%= f.number_field :seimaibuai , class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "登録", class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/sakes/edit.html.erb
<h1>日本酒情報の編集</h1>

<%= render 'form' %>

<%= link_to 'もどる', @sake %> |
<%= link_to '一覧にもどる', sakes_path %>

app/views/sakes/index.html.erb
<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>SakeDict. 日本酒辞典</h1>
    <p>日本酒の情報共有サイトです。銘柄追加、レビュー投稿できます！</p>
    <p><%= link_to "アカウントを作成する", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <h1>日本酒一覧</h1>
  <% @sakes.each do |sake| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
	<%= link_to (image_tag sake.image.url(:medium), dlass: 'image'), sake %>
  <div class="sake-name">
  <%= sake.name %>
  </div>
      </div>
    </div>
  <% end %>
</div>

app/views/sakes/new.html.erb
<h1>日本酒の新規追加</h1>

<%= render 'form' %>

<%= link_to '一覧にもどる', sakes_path %>

app/views/sakes/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">

      <div class="col-md-4">
	<%= image_tag @sake.image.url(:medium) %>

	<div class="star-rating" data-score= <%= @avg_review %>></div>
	<em><%= "#{@reviews.length} 件のレビュー" %></em>

	<div class="table-responsive">
	  <table class="table">
	    <tbody>
	      <tr>
		<td><strong>銘柄名</strong></td>
		<td><%= @sake.name %></td>
	      </tr>
	      <tr>
		<td><strong>詳細説明</strong></td>
		<td><%= @sake.description %></td>
	      </tr>
	      <tr>
		<td><strong>URL</strong></td>
		<td><%= @sake.url %></td>
	      </tr>
	      <tr>
		<td><strong>産地</strong></td>
		<td><%= @sake.home %></td>
	      </tr>
	      <tr>
		<td><strong>蔵元</strong></td>
		<td><%= @sake.maker %></td>
	      </tr>
	      <tr>
		<td><strong>分類</strong></td>
		<td><%= @sake.classification %></td>
	      </tr>
	      <tr>
		<td><strong>アルコール度数</strong></td>
		<td><%= @sake.alcohol %></td>
	      </tr>
	      <tr>
		<td><strong>原料名</strong></td>
		<td><%= @sake.ingredient %></td>
	      </tr>
	      <tr>
		<td><strong>原料米</strong></td>
		<td><%= @sake.rice %></td>
	      </tr>
	      <tr>
		<td><strong>精米歩合</strong></td>
		<td><%= @sake.seimaibuai %></td>
	      </tr>
	    </tbody>
	  </table>
	</div>
      </div>

      <div class="col-md-7 col-md-offset-1">
	<h1 class="review_title"><%= @sake.name %></h1>
	<p><%= @sake.catchcopy %></p>
	<%= link_to "レビュー投稿", new_sake_review_path(@sake), class: "btn btn-success" %>

	<% if @reviews.blank? %>
	  <h3>まだレビューがありません。投稿してください！</h3>
	<% else %>
	  <% @reviews.each do |review| %>
	    <div class="reviews">
	      <div class="star-rating" data-score= <%= review.rating %> ></div>
	      <p><%= review.comment %></p>
	    </div>
	  <% end %>
	<% end %>
      </div>

    </div>
  </div>
</div>

<%= link_to '編集する', edit_sake_path(@sake) %> |
<%= link_to '一覧にもどる', sakes_path %>

<script>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>